### ISSUE TITLE
Complete strategy backtest logic

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#26]
# Problem

Currently, strategy backtesting logic is incomplete. 

The strategy selector is hardcoded and does not allow the user to select an asset to swap. As a result, the results of the backtest   for a given strategy is averaged out across the entire portfolio.

The original flow:
1. Select an asset
2. Select percentage of asset to swap
3. Calculate value at current prices
4. Swap asset for strategy asset in current portfolio allocation
5. Calculate portfolio performance over same time series
6. Overlay on graph
7. Update portfolio allocation table and risk metrics

**Steps one and four are missing**

# Solution

Update strategy selection panel with:
• Asset dropdown that allows the user to select an asset from the set of treasury assets  
• Replace 'Review Order' button with 'Run'

**Comment by vaughnmck** [comment]
🙏

What interaction selects an asset?

**Comment by lajarre** [comment]
> What interaction selects an asset?

A click on the row in the assets table.
