### ISSUE TITLE
Add monitoring

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#28]
We are not currently tracking usage metrics. 

We should add usage monitoring so we can determine if we are generating repeat visitors. 

Repeat visits help us determine whether we are approaching product-market fit.

**Comment by lajarre** [comment]
To track:

- per-cookie usage. ⚠️ gpdr & ccpa
- server usage. Heroku has probably that for a price.
- crash logs. Sentry or just look at server logs from time to time.

**Comment by lajarre** [comment]
For now added Plausible and Sentry. Might need to add server usage monitoring later.
