### ISSUE TITLE
Web server timeout issues in production

### ISSUE THREAD

**Issue by lajarre** [butterdao/whip#49]
For treasuries with a large number of tokens, requests are taking long. When >30s, Heroku times them out.

The categories of solutions I see:

- Use a longer-living connection setup. It seems websockets might work straight out-of-the-box.
- Improving performance:
    - Store price and treasuries data in database, then each day just append the last day data that we got from data providers. That will not reduce the number of i/o requests to data providers but will significantly reduce the bandwidth of such requests. Also, this can provide a fallback in case new data isn't yet available.
    - Each day, populate the database and caches with a scheduled job. This way, ideally, for treasuries already in cache/db, calling our endpoint would result in no data provider i/o, being thus as fast as possible. But this is not helping for new treasuries.
- Change infrastructure provider: that's a pretty expensive effort and I feel like anyways Heroku is being reasonable with their defined timeout policy.

**Comment by acemasterjb** [comment]
Regarding solution 1, do you mean using websockets vs the FastAPI solution we're using right now?

I can work on solution 2. Solution 2.2 is basically almost done as it's more or less implemented but not currently being used. The frequency for the scheduled caching right now is 30s but this can be bumped up to 1 day.

**Comment by lajarre** [comment]
> Regarding solution 1, do you mean using websockets vs the FastAPI solution we're using right now?

FastAPI is already embedding [starlette](https://www.starlette.io/) for us, hence it seems that's a very simple change to make.

> I can work on solution 2. Solution 2.2 is basically almost done as it's more or less implemented but not currently being used. The frequency for the scheduled caching right now is 30s but this can be bumped up to 1 day.

Yes let's do this. It seems to me that there is a non-trivial issue to figure out: we need to store treasuries that have already been queried. The straightforward solution would be to add an array of treasury addresses in db. But there is a caveat about data persistence (see my remark below about having another db).  
We could also get a treasury list from a well-known source and build cache for all of them. That's actually probably a simpler thing to implement and will give us more of a headstart.  
Also, we could think about building cache for all erc20 tokens that are listed in the uniswap tokenlist. That would allow to already have interesting data even for new treasuries.

If you decide to follow either of the two last options, we might need first to look at how big the Redis instance needs to be in terms of memory.

I'll try to think about the database solution (relative to 2.2). It seems to me we should use a different db than the existing Redis one, as we already started optimising the current Redis db for being used as a LRU cache whereas the new db should be about long-lived data. I'll try to assess other dbs as well.

**Comment by acemasterjb** [comment]
>  It seems to me we should use a different db than the existing Redis one, as we already started optimising the current Redis db for being used as a LRU cache whereas the new db should be about long-lived data.

Just so that I understand, you're thinking about using Redis for hot storage and another db as cold storage? If so, I agree. Redis was always meant to be a quick and easily manageable solution to achieve a "correct" solution in time of the Hackathon deadline.

Since we have to think about caching more data to be faster, I agree that we should introduce another db for infrequent data.

Another remark about optimisation, I will soon push a PR to address 2.2. I found CryptoStats, we can use to get a list of the addresses of major DAO treasuries. It is quite a comprehensive list which can query to prepopulate our cache, and now I am thinking we should a map/hash map (using `set`/`hset` respectively).

The reason being that it would be too expensive to check if the treasury exists using a Redis "array" (which is actually a linked list). With a hash map/map I'm pretty sure it will take O(1) time to do this necessary check.

```python
# current implementation
def store_treasury_metadata(address: str, chain_id: int = CHAIN_ID):
    for _addr, _chain_id in (json.loads(t) for t in db.lrange("treasuries", 0, -1)):
        if (_addr, _chain_id) == (address, chain_id):
            return
    db.rpush("treasuries", json.dumps([address, chain_id]))
```

**Comment by lajarre** [comment]
> Just so that I understand, you're thinking about using Redis for hot storage and another db as cold storage? If so, I agree. Redis was always meant to be a quick and easily manageable solution to achieve a "correct" solution in time of the Hackathon deadline.
> 
> Since we have to think about caching more data to be faster, I agree that we should introduce another db for infrequent data.

Yes.

> The reason being that it would be too expensive to check if the treasury exists using a Redis "array" (which is actually a linked list). With a hash map/map I'm pretty sure it will take O(1) time to do this necessary check.

You probably want to use sets: https://redis.io/docs/manual/data-types/

**Comment by lajarre** [comment]
Closing this in favor of https://github.com/butterdao/whip/issues/91 https://github.com/butterdao/whip/issues/62 https://github.com/butterdao/whip/issues/66
