### ISSUE TITLE
Risk contributions for stablecoins are negative 

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#64]
<img width="828" alt="Screenshot 2022-06-29 at 13 30 18" src="https://user-images.githubusercontent.com/7321643/176499418-b1ea34f8-516f-4f5b-a807-0ed940d46fa6.png">

Risk contributions for stablecoins, e.g. USDC & USDT are negative as seen in the above screenshot.

**Comment by lajarre** [comment]
It seems to me there is no reason why the risk contribution shouldn't be negative.

Our calculations are based on this spec: https://rviews.rstudio.com/2017/09/13/asset-contribution-to-portfolio-volatility/

See this for an idea how that makes sens (not scientific): https://support.everysk.com/hc/en-us/articles/360003521754-MCTR-for-long-short-portfolios

To be double checked by an expert in the matter.

If that makes sense, we can close the issue for now @vaughnmck .

**Comment by vaughnmck** [comment]
Sorry, I missed this. Happy to close. 

Still unsure whether we've implemented risk contribution or marginal contribution to risk. I believe it is the former and that this has an impact on whether or not risk contribution can be negative but I need some more time to be confident.
