### ISSUE TITLE
Token allocation can be negative

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#71]
<img width="804" alt="Screenshot 2022-07-06 at 10 32 03" src="https://user-images.githubusercontent.com/7321643/177575128-7d77a3ea-6e10-46ef-a223-f1564b92c175.png">

**Steps to repro:**
1. Go to [Radicle's treasury](https://whip.buttery.money/?address=0x8da8f82d2bbdd896822de723f55d6edf416130ba)
2. Select USDC Spread strategy
3. Select RAD
4. Select Preview

**Comment by lajarre** [comment]
Fixed in #82.
