### ISSUE TITLE
Gnosis OWL token not producing a CoinGecko price feed

### ISSUE THREAD

**Issue by acemasterjb** [butterdao/whip#72]
## Summary
Gnosis' [OWL token](https://blog.gnosis.pm/owl-token-use-cases-6094027ecb37) is causing a number of issues when calculating volatility and risk contribution. This is due to CoinGecko (CG) [not providing any price feed data for this token past 29/01/22](https://api.coingecko.com/api/v3/coins/ethereum/contract/0x1a5f9352af8af974bfc03399e3767df6370d82e4/market_chart/range?vs_currency=usd&from=1625443200.0&to=1657065600.0).

## Details
Because of this issue, any observations provided by Whip past 29/01/22 simply cannot:
* provide stats reliable statistics for historical balances of this asset on a given treasury
* calculate the volatility of this asset after 29/01/22
* calculate the risk contribution of this asset vs others in a given treasury's portfolio

## Possible Solutions
* Provide a check to ensure that CG responses are continuous up until "today".
    * Then use a fallback pricefeed data provider to fill in the gaps/replace the incomplete price feed
* Create our own database of price feed data for this and other tokens (in accordance with #62)

**Comment by vaughnmck** [comment]
I prefer the first solution. 

As a principle, we should have a preference for simplicity, then correctness, then speed.

If CG has a random data gap for one token, which [is important to us](https://www.notion.so/butterd/Gnosis-DAO-3a25f8215b3a4fb78b7dd9b72349d162), finding another data source that has the data seems a lot simpler than building our own db. At least until we're sure that what we've built solves the problem for treasury managers at Gnosis.

Have you ever tested Zerion's API: https://docs.zerion.io/websockets/namespaces/address

**Comment by acemasterjb** [comment]
I took a look at Zerion's API and have been playing around with it a bit, but I don't think this can be used as a fallback for historical pricefeed data.

The closest thing I could find for a solution is on their `/assets` namespace under the `charts` scope, but this only gives the historical pricefeed based on a "asset code". Unfortunately, "own" or "OWL" is not one of the supported codes. The `chart` scope on  `addresses` I hoped would be the solution we are looking for, but seems like it would be better off as a potential fallback/replacement for the covalent endpoints (historical portfolio balance maybe?). It's not really clear due to a lack of documentation.

**Comment by vaughnmck** [comment]
That's disappointing. Do you have an alternative backup API? How would you suggest we proceed?

**Comment by acemasterjb** [comment]
Strange enough, Covalent (who says they get their price feed data from CG) seems to be a viable solution for us.

See: https://api.covalenthq.com/v1/pricing/historical_by_addresses_v2/1/USD/0x1A5F9352Af8aF974bFC03399e3767DF6370d82e4/?quote-currency=USD&format=JSON&from=2021-07-11&page-size=&key=ckey_30f56650f3a544fe8803d522cb0

notice the `from` is `2021-07-11` and that the response from the above link seems to have monotonic data. Really strange but whatever. Will implement this only as a fallback for now.

**Comment by vaughnmck** [comment]
If it works, it works. Perhaps they ran into this issue and found a good backup

We can come up with a better solution when we have more resources to spare.
