### ISSUE TITLE
ETH diversification strategy

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#74]
# Problem

Whip can currently be used to backtest USDC, however [Radicle are considering diversification into ETH](https://radicle.community/t/make-eth-investment-with-treasury-usdc-funds/2882/11) using their existing USDC holdings. Whip cannot currently support ETH backtests.

![Image](https://user-images.githubusercontent.com/7321643/178047453-1d1bcac5-8202-444c-91cb-c086eb545ea0.png)

# Solution

Implement the ETH strategy

**Comment by acemasterjb** [comment]
Seems like the changes to  the backend are pretty simple.

@lajarre made a new branch with some changes to [endpoint.py](https://github.com/butterdao/whip/blob/feature/spread_eth/backend/app/endpoints.py#L126-L167). Let me know if it looks good.

**Comment by lajarre** [comment]
We still need to make the frontend change.

**Comment by acemasterjb** [comment]
Auto close due to PR merge, my apologies 😅.
